LLVM / Clang Support
This patch provides support for compiling Bareflank with
Clang / LLVM.

GCC is still needed to compile NewLib (they are tied at the hip),
and we are currently still using LD from Binutils as LLD from
LLVM is still in heavy development. For this reason, GCC has
been paired with Clang / LLVM as follows:
- Clang 3.8 with GCC 5.2.0
- Clang 3.9 with GCC 6.2.0

Someday, once C++17 and LLD are ready, and we have our own
libc, we will updated Bareflank to use Clang / LLVM
exclusively as this would remove the need for docker as our
own cross compilers (for x86 at least).

To try out LLVM / Clang, use the --use_llvm_clang flag when
setting up, or running configure. Docker has been updated
and the local compiler scripts will also build clang as
needed.

Signed-off-by: “Rian <“rianquinn@gmail.com”>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20,7 +20,7 @@
 # License along with this library; if not, write to the Free Software
 # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 
-version=3
+version=4
 
 # ------------------------------------------------------------------------------
 # Colors
@@ -34,7 +34,7 @@ CE='\033[0m'
 # Flags
 # ------------------------------------------------------------------------------
 
-CROSS_COMMONFLAGS="-fpic -ffreestanding -mno-red-zone -fexceptions -fstack-protector-strong -D_FORTIFY_SOURCE=2 -mtune=sandybridge -march=sandybridge -mstackrealign -D_HAVE_LONG_DOUBLE -D_LDBL_EQ_DBL -D_POSIX_TIMERS -U__STRICT_ANSI__ -DMALLOC_PROVIDED -DCLOCK_MONOTONIC"
+CROSS_COMMONFLAGS="-fpic -ffreestanding -mno-red-zone -fexceptions -fstack-protector-strong -D_FORTIFY_SOURCE=2 -mtune=native -march=native -mstackrealign -D_HAVE_LONG_DOUBLE -D_LDBL_EQ_DBL -D_POSIX_TIMERS -U__STRICT_ANSI__ -DMALLOC_PROVIDED -DCLOCK_MONOTONIC"
 CROSS_CCFLAGS="-std=c99 $CROSS_COMMONFLAGS"
 CROSS_CXXFLAGS="-std=c++14 -fno-use-cxa-atexit -fno-threadsafe-statics $CROSS_COMMONFLAGS"
 
@@ -109,6 +109,7 @@ check_env() {
         echo "export LLVM_RELEASE=\"release_39\"" >> $BUILD_ABS/env.sh
         echo "export module_file=\"$module_file\"" >> $BUILD_ABS/env.sh
         echo "export compiler=\"$compiler\"" >> $BUILD_ABS/env.sh
+        echo "export USE_LLVM_CLANG=\"$USE_LLVM_CLANG\"" >> $BUILD_ABS/env.sh
         echo "export CFLAGS=\"$CROSS_CCFLAGS\"" >> $BUILD_ABS/env.sh
         echo "export CXXFLAGS=\"$CROSS_CXXFLAGS\"" >> $BUILD_ABS/env.sh
         printf "export extensions=\"" >> $BUILD_ABS/env.sh
@@ -139,10 +140,6 @@ setup_environment_variables() {
     if [[ -z "$module_file" ]]; then
         module_file=$HYPER_ABS/bfm/bin/native/vmm.modules
     fi
-
-    if [[ -z "$compiler" ]]; then
-        compiler=gcc_520
-    fi
 }
 
 # ------------------------------------------------------------------------------
@@ -160,7 +157,8 @@ option_help() {
     echo -e "       -r, --update_makefiles           updates makefiles only"
     echo -e "       -m, --module_file <filename>     module_file to use"
     echo -e "       -e, --extension <dirname>        directory of extension"
-    echo -e "       -g, --compiler <dirname>         directory of cross compiler"
+    echo -e "           --compiler <dirname>         directory of cross compiler"
+    echo -e "           --use_llvm_clang             use LLVM / Clang where possible"
     echo -e ""
 }
 
@@ -398,6 +396,7 @@ copy_makefile() {
     echo -e "BUILD_ABS:=$BUILD_ABS" >> $1/Makefile.tmp
     echo -e "HYPER_REL:=$2" >> $1/Makefile.tmp
     echo -e "BUILD_REL:=$1" >> $1/Makefile.tmp
+    echo -e "USE_LLVM_CLANG:=$USE_LLVM_CLANG" >> $1/Makefile.tmp
     echo -e "CONFIGURED_CROSS_CCFLAGS:=$CROSS_CCFLAGS" >> $1/Makefile.tmp
     echo -e "CONFIGURED_CROSS_CXXFLAGS:=$CROSS_CXXFLAGS" >> $1/Makefile.tmp
     echo -e "MAKEFILE_ABS:=\$(dir \$(abspath \$(lastword \$(MAKEFILE_LIST))))" >> $1/Makefile.tmp
@@ -629,6 +628,8 @@ create_root_makefile() {
 # Filter Arguments
 # ------------------------------------------------------------------------------
 
+compiler="gcc_520"
+
 i=0
 extensions[$i]=
 
@@ -670,6 +671,10 @@ while [[ $# -ne 0 ]]; do
         this_is_make="true"
     fi
 
+    if [[ $1 == "--use_llvm_clang" ]]; then
+        use_llvm_clang="true"
+    fi
+
     if [[ $1 == "-m" ]] || [[ $1 == "--module_file" ]]; then
         shift
 
@@ -681,7 +686,7 @@ while [[ $# -ne 0 ]]; do
         module_file=`realpath $1`
     fi
 
-    if [[ $1 == "-g" ]] || [[ $1 == "--compiler" ]]; then
+    if [[ $1 == "--compiler" ]]; then
         shift
         compiler=$1
     fi
@@ -701,5 +706,10 @@ while [[ $# -ne 0 ]]; do
     shift
 
 done
+
+if [[ $USE_LLVM_CLANG == "true" ]] && [[ $compiler != "gcc_520" ]] && [[ $compiler != "gcc_620" ]]; then
+    echo "ERROR: Clang is only supported with GCC 5.2 and GCC 6.2"
+    exit 1
+fi
 
 option_run
